version: "3.5"

services:
  frontend:
    build:
      context: ./frontend
    container_name: weather-frontend
    restart: always
    command: bash -c "npm start"

  nginx:
    build:
      context: ./nginx
    ports:
      - 8000:80
    container_name: weather-nginx
    restart: always
    depends_on:
      - frontend
